### ISSUE TITLE
Invalid availability zone: [ap-southeast-2] 

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/sample-code#135]
Create a stack using CloudFormation

```
---
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-southeast-2
      ImageId: ami-da2ac3b8
      InstanceType: t2.micro
```

Get error

```
Invalid availability zone: [ap-southeast-2] (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 93a4540e-e10e-4a6c-ac0e-05d872b73430)
```
