### ISSUE TITLE
SSM Secure reference is not supported in: [AWS::ECS::TaskDefinition/Properties/ContainerDefinitions/Environment]

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/sample-code#272]
Cloudformation template:

```Value: {{resolve:ssm-secure:accessKeySecretKey:1}}```

Get error:

```
An error occurred (ValidationError) when calling the CreateStack operation: SSM Secure reference is not supported in: [AWS::ECS::TaskDefinition/Properties/ContainerDefinitions/Environment]
```

**Comment by sunmingtao** [comment]
Turns out cloudformation doesn't support secureString. 

https://stackoverflow.com/questions/56891180/referencing-aws-parameter-stores-secure-string-in-cloudformation-template

Switch to plain string

```
Parameters:
  AccessKeySecretKey:
    Type: 'AWS::SSM::Parameter::Value<String>'

....

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ...
      ContainerDefinitions:
        ...
          Environment:
            - Name: JAVA_OPTS
              Value: !Ref AccessKeySecretKey
```


```
aws cloudformation create-stack --stack-name soccer-bet-stack --template-body file://./ecs.yml --capabilities CAPABILITY_NAMED_IAM --parameters ParameterKey=AccessKeySecretKey,ParameterValue=accessKeySecretKey
```
